[aws]
symbol=" "
[dart]
symbol=" "
[docker_context]
symbol=" "
[elixir]
symbol=" "
[elm]
symbol=" "
[erlang]
symbol=" "
[gcloud]
symbol=" "
[git_status]
style="bold green"
[git_branch]
symbol=" "
[golang]
symbol=" "
[java]
symbol=" "
[lua]
symbol=" "
[memory_usage]
symbol=" "
[nix_shell]
symbol=" "
[openstack]
symbol=" "
[package]
symbol=" "
[perl]
symbol=" "
[php]
symbol=" "
[python]
symbol=" "
[ruby]
symbol=" "
[rust]
symbol=" "
[status]
format="[(SIG$signal_name )]($style)"
disabled=false
[swift]
symbol=" "
